1. an open-source Python package is most widely used for data science/data analysis and machine learning tasks

2. series and data frames

3. Data Cleansing, Data Normalization, Data visualization, Data inspection

4. equals true 

5. data file composed of spreadsheets

6. null values


In [67]:
import numpy as np
import pandas as pd
import copy



In [78]:
7. 
arr1 = np.array([[1, 3, 2], [6, 7, 8], [4, 5, 9], [8, 10, 11], ])
print(np.sort(arr1))
arr1 = np.reshape(arr1,(2,3,2))





[[ 1  2  3]
 [ 6  7  8]
 [ 4  5  9]
 [ 8 10 11]]


In [27]:
8.
np.linspace(0, 20)


array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [28]:
import copy 



In [31]:
9. 
array2 = [ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ]
array3 = copy.deepcopy(array2)
print(array3)

[0.0, 0.40816327, 0.81632653, 1.2244898, 1.63265306, 2.04081633, 2.44897959, 2.85714286, 3.26530612, 3.67346939, 4.08163265, 4.48979592, 4.89795918, 5.30612245, 5.71428571, 6.12244898, 6.53061224, 6.93877551, 7.34693878, 7.75510204, 8.16326531, 8.57142857, 8.97959184, 9.3877551, 9.79591837, 10.20408163, 10.6122449, 11.02040816, 11.42857143, 11.83673469, 12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102, 14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735, 16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367, 18.36734694, 18.7755102, 19.18367347, 19.59183673, 20.0]


In [106]:
10.
arraya = np.array([[25, 16]])
arrayb = np.array([[11,2],
                    [13, 4]])
arrayc = np.array([[7, 81],
                    [5, 6], 
                    [11, 12]])


In [107]:
Newarray = np.concatenate((arraya, arrayb, arrayc))


In [71]:
11.
print(np.sort(Newarray))


[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [113]:
12.

reShapedArrays = ([[16, 25],
 [2, 11],
 [4, 13],
 [7, 81],
 [5,  6],
 [11, 12]])
a = reShapedArrays
print("[16, 25], [2, 11]", a)
b = reShapedArrays
print("[4, 13], [7, 81]", b )
c = reShapedArrays
print("[5, 6]", c)
d = reShapedArrays
print("[11, 12]", d )



[16, 25], [2, 11] [[16, 25], [2, 11], [4, 13], [7, 81], [5, 6], [11, 12]]
[4, 13], [7, 81] [[16, 25], [2, 11], [4, 13], [7, 81], [5, 6], [11, 12]]
[5, 6] [[16, 25], [2, 11], [4, 13], [7, 81], [5, 6], [11, 12]]
[11, 12] [[16, 25], [2, 11], [4, 13], [7, 81], [5, 6], [11, 12]]


In [47]:
13.
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

In [50]:
comboArray = np.concatenate((one, two, three))
print(comboArray)
print(np.sort(comboArray))

[10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [139]:
14. 
print(comboArray[1:2])
print(comboArray[2:])
print(comboArray[3:14])
print(comboArray[-6:])
print(comboArray[-1:15])
print(comboArray[8::2])
print(comboArray[-1::-5])

[11]
[12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
[13 14 15 16 17 20 21 22 23 24 25]
[2 3 4 5 6 7]
[]
[20 22 24 26  0  2  4  6]
[ 7  2 25 20 13]


In [83]:
15. 
import numpy as np 
import pandas as pd

Dinner = {
"ingredients": ["Flour", "Milk", "Eggs", "Spam"],
"quantity": [4, 1, 2, 1],
"unit": ["cups", "cup", "large", "can"]
}



In [84]:
results = pd.DataFrame(Dinner)
print(results)


  ingredients  quantity   unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


In [85]:
16.
studentData = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }


In [86]:
students = pd.DataFrame(studentData)
print(students)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [151]:
17. 
students['deserts'] = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
print(students)

      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  


In [179]:
18.
students.sort_values(by = ['Name', 'address'], inplace = True)


In [187]:
19.
cows_and_goats = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

In [188]:
df.to_csv('cows_and_goats.csv')
print(cows_and_goats)

        Cows  Goats
Year 1    12     22
Year 2    20     19


In [190]:
20. 
veggies_avocados = pd.DataFrame({"avocado", "guacamole", "toast"})
df.to_csv('veggies_avocados.csv')
print(veggies_avocados)


           0
0    avocado
1      toast
2  guacamole


In [198]:


veggies_avocados.to_csv('veggies_spinach.csv')
